name: Deploy Frontend to Azure Storage
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for clean builds

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm' # Cache npm dependencies for faster builds

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables for Build
      run: |
        echo "REACT_APP_API_BASE_URL=https://mern-crud-backend-cjbjgcbjbgd5czdu.southeastasia-01.azurewebsites.net/api/persons" >> $GITHUB_ENV
      shell: bash

    - name: Build Frontend
      run: npm run build
      env:
        REACT_APP_API_BASE_URL: ${{ env.REACT_APP_API_BASE_URL }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

    - name: Deploy to Azure Storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name merncrudfrontend --auth-mode login --source ./dist --destination '$web' --overwrite
      env:
        AZURE_STORAGE_ACCOUNT: merncrudfrontend # Optional: Explicitly set for clarity

    - name: Logout from Azure
      run: az logout
      if: always()